name: smartlets
description: A Flutter project for Smartlets-mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # Draw SVG files on a Flutter Widget.
  flutter_svg: any
  ###
  ### Firebase Packages ###
  ###
  firebase_core: ^0.5.0
  # Firebase authentication
  firebase_auth: ^0.18.0+1
  # Google services & Authentication
  google_sign_in: ^4.5.3
  # A Flutter plugin to use the Cloud Firestore API.
  cloud_firestore: ^0.14.0+2
  # For Facebook authentication
  flutter_login_facebook: ^0.2.1
  # Check Internet connectivity
  data_connection_checker: ^0.3.4
  # Service locator
  get_it: ^4.0.4
  # Flutter BloC for state management
  flutter_bloc: ^6.0.5
  # Automatically persists and restores bloc states
  hydrated_bloc: ^6.0.1
  # A lightweight and blazing fast key-value database written in pure Dart.
#  hive: ^1.4.4
  # Functional Programming
  dartz: ^0.9.1
  # For regular Unions
  freezed_annotation: ^0.11.0+1
  # For generating unique UUIDs
  uuid: ^2.2.2
  # Flutter widget that automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^2.1.0
  # simplifies dependency injection
  injectable: ^1.0.4
  # provides internationalization
  # and localization facilities
  intl: ^0.16.1
  # A declarative routing solution
  auto_route: ^0.6.7
  # Helpful package for manipulating "overlays":
  flutter_portal: ^0.1.0
  # A flutter navigation observer that adds access to lists
  # that track the navigation stack both forwards and backwards.
  navigation_history_observer: ^1.0.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  bloc_test: any
  logger: any
  flutter_launcher_icons: any
  # Code Generators
  build_runner: any
  freezed: any
  injectable_generator: any
  built_value_generator: any
  auto_route_generator: any

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
